[package]
name = "erc721-example"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version = "0.0.0"

[dependencies]
contracts = { path = "../../contracts", features = ["erc721_pausable", "erc721_burnable"] }
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
stylus-sdk.workspace = true
stylus-proc.workspace = true
mini-alloc.workspace = true

[lib]
crate-type = ["lib", "cdylib"]